  mysql:
    image: mysql
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
    environment:
      MYSQL_ROOT_PASSWORD: default
      MYSQL_USER: mysql
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: performacermi
    ports:
      - 3306:3306